"""Offline, non-executing contracts for the Insider Buying research lane.

This package deliberately has no network collection, outcome, portfolio,
broker, or scheduler surface. It contains immutable in-memory Form 4
structure, a fixture parser, and a caller-supplied SEC quarterly ZIP integrity
boundary plus explicit-profile, offline parsed, EDGAR acceptance-evidence, and
observation-only Form 4/A chronology and multi-period supplied-link-evidence
boundaries, plus an evidence-bound provisional disposition/quarantine report
and its immutable, upstream-rebuilt snapshot boundary.  The package also
exposes the zero-authority IB-1I four-family research gate without allocating
a confirmatory cell or permanent look, plus the observed-only IB-2A normalized
identity inventory that leaves every point-in-time resolution gate closed.
It also exposes the IB-2B exact-SEC-CIK grouping boundary, which retains every
issuer and reporting-owner observation and quarantines ambiguous attribution.
The IB-2C boundary maps those exhaustive transactions against caller-supplied,
dated security/title/ticker references while retaining zero external authority.
IB-2D adds exhaustive provisional lot diagnostics and an exact USD 50,000
comparison while retaining every downstream authority gate as false.
IB-3A adds synthetic-only event-size, freshness, raw-score, and breadth
equation diagnostics; it does not consume IB-2D or expose a canonical score.
"""

from research.insider_buying.contracts import (
    CANONICAL_SPEC,
    ClassificationOutcome,
    FilingCorpus,
    FilingEnvelope,
    ParsedFiling,
    ParsedTransaction,
    PublicAvailability,
    ReportingOwner,
    TransactionDiagnostic,
    build_filing_corpus,
)
from research.insider_buying.form4_xml import Form4ParseError, parse_form4_xml
from research.insider_buying.form4_amendment_reconciliation import (
    FORM4_AMENDMENT_RECONCILIATION_VERSION,
    Form4AmendmentLineage,
    Form4AmendmentReconciliationError,
    Form4AmendmentReconciliationIdentity,
    Form4ObservedState,
    Form4VersionDisposition,
    Form4VersionInterval,
    ReconciledForm4Amendments,
    SecForm4XmlSource,
    SecForm4XmlSourceIdentity,
    reconcile_sec_form4_amendments,
)
from research.insider_buying.form4_multi_period_amendment_evidence import (
    FORM4_MULTI_PERIOD_EVIDENCE_VERSION,
    Form4MultiPeriodEvidenceError,
    Form4MultiPeriodEvidenceIdentity,
    ProfileBoundForm4AmendmentEvidence,
    SecEdgarAcceptancePeriodIdentity,
    SecEdgarAcceptancePeriodInput,
    SecForm4AmendmentEvidenceProfile,
    SuppliedForm4AmendmentLinkEvidence,
    assemble_sec_form4_multi_period_evidence,
)
from research.insider_buying.form4_provisional_disposition_report import (
    FORM4_PROVISIONAL_DISPOSITION_REPORT_VERSION,
    Form4ProvisionalDisposition,
    Form4ProvisionalDispositionReport,
    Form4ProvisionalDispositionReportError,
    Form4ProvisionalDispositionReportIdentity,
    Form4ProvisionalDispositionRow,
    build_form4_provisional_disposition_report,
)
from research.insider_buying.form4_provisional_disposition_snapshot import (
    FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_KIND,
    FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_VERSION,
    Form4ProvisionalDispositionSnapshotError,
    load_form4_provisional_disposition_snapshot,
    write_form4_provisional_disposition_snapshot,
)
from research.insider_buying.form4_observed_identity_inventory import (
    FORM4_OBSERVED_IDENTITY_INVENTORY_VERSION,
    Form4ObservedFilingIdentityRow,
    Form4ObservedIdentityDisposition,
    Form4ObservedIdentityInventory,
    Form4ObservedIdentityInventoryError,
    Form4ObservedIdentityInventoryIdentity,
    Form4ObservedOwnerSetOutcome,
    Form4ObservedReportingOwnerIdentityRow,
    Form4ObservedTransactionIdentityRow,
    build_form4_observed_identity_inventory,
)
from research.insider_buying.form4_sec_entity_grouping import (
    FORM4_SEC_ENTITY_GROUPING_VERSION,
    Form4OwnerAttributionOutcome,
    Form4SecEntityGrouping,
    Form4SecEntityGroupingError,
    Form4SecEntityGroupingIdentity,
    Form4SecIssuerIdentityCandidate,
    Form4SecIssuerObservation,
    Form4SecReportingOwnerIdentityCandidate,
    Form4SecReportingOwnerObservation,
    Form4SecTransactionAttributionRow,
    build_form4_sec_entity_grouping,
)
from research.insider_buying.form4_pit_security_mapping import (
    FORM4_PIT_SECURITY_MAPPING_VERSION,
    Form4PitSecurityMapping,
    Form4PitSecurityMappingError,
    Form4PitSecurityMappingIdentity,
    Form4PitSecurityMappingOutcome,
    Form4PitSecurityMappingRow,
    Form4PitSecurityRecord,
    Form4SecurityClass,
    Form4SecurityTitleInterval,
    Form4SecurityTitleMappingKind,
    Form4TickerInterval,
    build_form4_pit_security_mapping,
)
from research.insider_buying.form4_provisional_lot_diagnostics import (
    FORM4_PROVISIONAL_LOT_DIAGNOSTICS_VERSION,
    FORM4_PROVISIONAL_LOT_THRESHOLD_USD,
    Form4ProvisionalLotDiagnosticRow,
    Form4ProvisionalLotDiagnostics,
    Form4ProvisionalLotDiagnosticsError,
    Form4ProvisionalLotDiagnosticsIdentity,
    Form4ProvisionalLotDisposition,
    Form4ProvisionalLotGroup,
    Form4ProvisionalLotQuarantineReason,
    Form4ProvisionalLotThresholdDiagnostic,
    build_form4_provisional_lot_diagnostics,
)
from research.insider_buying.form4_stock_signal_formula_diagnostics import (
    FORM4_STOCK_SIGNAL_DECIMAL_PRECISION,
    FORM4_STOCK_SIGNAL_DECIMAL_ROUNDING,
    FORM4_STOCK_SIGNAL_DOLLAR_BREADTH_FORMULA,
    FORM4_STOCK_SIGNAL_EVENT_SCORE_FORMULA,
    FORM4_STOCK_SIGNAL_FORMULA_DIAGNOSTICS_VERSION,
    FORM4_STOCK_SIGNAL_FRESHNESS_EVALUATION,
    FORM4_STOCK_SIGNAL_FRESHNESS_FORMULA,
    FORM4_STOCK_SIGNAL_HALF_LIFE_TRADING_DAYS,
    FORM4_STOCK_SIGNAL_LOOKBACK_TRADING_DAYS,
    FORM4_STOCK_SIGNAL_MINIMUM_PURCHASE_VALUE_USD,
    FORM4_STOCK_SIGNAL_NUMERIC_POLICY_HASH,
    FORM4_STOCK_SIGNAL_RAW_SCORE_FORMULA,
    FORM4_STOCK_SIGNAL_SIZE_FORMULA,
    MAX_FORM4_STOCK_SIGNAL_AGE_TRADING_DAYS,
    MAX_FORM4_STOCK_SIGNAL_EVENTS,
    MAX_FORM4_STOCK_SIGNAL_PROJECTION_DEPTH,
    MAX_FORM4_STOCK_SIGNAL_PROJECTION_NODES,
    MAX_FORM4_STOCK_SIGNAL_ROLES_PER_EVENT,
    MAX_FORM4_STOCK_SIGNAL_TEXT_CHARACTERS,
    Form4StockSignalBreadthDiagnostics,
    Form4StockSignalEventContribution,
    Form4StockSignalFixtureEvent,
    Form4StockSignalFormulaDiagnostics,
    Form4StockSignalFormulaDiagnosticsError,
    Form4StockSignalFormulaIdentity,
    build_form4_stock_signal_fixture_event,
    build_form4_stock_signal_formula_diagnostics,
)
from research.insider_buying.sec_bulk_snapshot import (
    ALLOWED_SEC_TABLES,
    LoadedSecBulkSnapshot,
    SecBulkMember,
    SecBulkSnapshotError,
    SecBulkSnapshotIdentity,
    SecBulkSource,
    REQUIRED_SEC_TABLES,
    inspect_sec_bulk_archive,
    load_sec_bulk_snapshot,
    write_sec_bulk_snapshot,
)
from research.insider_buying.sec_bulk_parsed_snapshot import (
    LoadedSecBulkParsedSnapshot,
    ParsedSecBulkAccession,
    ParsedSecBulkRow,
    ParsedSecBulkTableIdentity,
    PARSED_SNAPSHOT_CONTRACT_VERSION,
    SEC_TSV_PARSER_VERSION,
    SecBulkParsedSnapshotError,
    SecBulkParsedSnapshotIdentity,
    SecTsvSchemaProfile,
    SecTsvSchemaVariant,
    build_sec_bulk_parsed_snapshot,
    load_sec_bulk_parsed_snapshot,
)
from research.insider_buying.sec_edgar_acceptance_snapshot import (
    EDGAR_ACCEPTANCE_SNAPSHOT_CONTRACT_VERSION,
    EDGAR_ACCEPTANCE_SNAPSHOT_KIND,
    LoadedSecEdgarAcceptanceSnapshot,
    SEC_EDGAR_METADATA_PARSER_VERSION,
    SecEdgarAcceptanceSnapshotError,
    SecEdgarAcceptanceSnapshotIdentity,
    SecEdgarAvailabilityRecord,
    SecEdgarAvailabilityRule,
    SecEdgarAvailabilityTier,
    SecEdgarMetadataSchemaProfile,
    SecEdgarMetadataSource,
    SecEdgarMetadataSourceIdentity,
    build_sec_edgar_acceptance_snapshot,
    load_sec_edgar_acceptance_snapshot,
)
from research.insider_buying.preregistration import (
    FIXED_STRATEGY_LANE_IDS,
    INSIDER_BUYING_BLUEPRINT_SHA256,
    INSIDER_BUYING_RESEARCH_GATE,
    INSIDER_BUYING_RESEARCH_GATE_SHA256,
    INSIDER_BUYING_RESEARCH_GATE_VERSION,
    InsiderBuyingAllocationState,
    InsiderBuyingPreregistrationError,
    InsiderBuyingResearchGate,
    InsiderBuyingSlotDisposition,
)

__all__ = [
    "ALLOWED_SEC_TABLES",
    "CANONICAL_SPEC",
    "ClassificationOutcome",
    "EDGAR_ACCEPTANCE_SNAPSHOT_CONTRACT_VERSION",
    "EDGAR_ACCEPTANCE_SNAPSHOT_KIND",
    "FORM4_AMENDMENT_RECONCILIATION_VERSION",
    "FORM4_MULTI_PERIOD_EVIDENCE_VERSION",
    "FORM4_OBSERVED_IDENTITY_INVENTORY_VERSION",
    "FORM4_PIT_SECURITY_MAPPING_VERSION",
    "FORM4_PROVISIONAL_DISPOSITION_REPORT_VERSION",
    "FORM4_PROVISIONAL_LOT_DIAGNOSTICS_VERSION",
    "FORM4_PROVISIONAL_LOT_THRESHOLD_USD",
    "FORM4_SEC_ENTITY_GROUPING_VERSION",
    "FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_KIND",
    "FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_VERSION",
    "FIXED_STRATEGY_LANE_IDS",
    "FilingCorpus",
    "FilingEnvelope",
    "Form4AmendmentLineage",
    "Form4AmendmentReconciliationError",
    "Form4AmendmentReconciliationIdentity",
    "Form4MultiPeriodEvidenceError",
    "Form4MultiPeriodEvidenceIdentity",
    "Form4ObservedFilingIdentityRow",
    "Form4ObservedIdentityDisposition",
    "Form4ObservedIdentityInventory",
    "Form4ObservedIdentityInventoryError",
    "Form4ObservedIdentityInventoryIdentity",
    "Form4ObservedOwnerSetOutcome",
    "Form4ObservedReportingOwnerIdentityRow",
    "Form4ObservedTransactionIdentityRow",
    "Form4OwnerAttributionOutcome",
    "Form4PitSecurityMapping",
    "Form4PitSecurityMappingError",
    "Form4PitSecurityMappingIdentity",
    "Form4PitSecurityMappingOutcome",
    "Form4PitSecurityMappingRow",
    "Form4PitSecurityRecord",
    "Form4ProvisionalDisposition",
    "Form4ProvisionalDispositionReport",
    "Form4ProvisionalDispositionReportError",
    "Form4ProvisionalDispositionReportIdentity",
    "Form4ProvisionalDispositionRow",
    "Form4ProvisionalDispositionSnapshotError",
    "Form4ProvisionalLotDiagnosticRow",
    "Form4ProvisionalLotDiagnostics",
    "Form4ProvisionalLotDiagnosticsError",
    "Form4ProvisionalLotDiagnosticsIdentity",
    "Form4ProvisionalLotDisposition",
    "Form4ProvisionalLotGroup",
    "Form4ProvisionalLotQuarantineReason",
    "Form4ProvisionalLotThresholdDiagnostic",
    "Form4SecEntityGrouping",
    "Form4SecEntityGroupingError",
    "Form4SecEntityGroupingIdentity",
    "Form4SecIssuerIdentityCandidate",
    "Form4SecIssuerObservation",
    "Form4SecReportingOwnerIdentityCandidate",
    "Form4SecReportingOwnerObservation",
    "Form4SecTransactionAttributionRow",
    "Form4SecurityClass",
    "Form4SecurityTitleInterval",
    "Form4SecurityTitleMappingKind",
    "Form4TickerInterval",
    "Form4ObservedState",
    "Form4ParseError",
    "Form4VersionDisposition",
    "Form4VersionInterval",
    "INSIDER_BUYING_BLUEPRINT_SHA256",
    "INSIDER_BUYING_RESEARCH_GATE",
    "INSIDER_BUYING_RESEARCH_GATE_SHA256",
    "INSIDER_BUYING_RESEARCH_GATE_VERSION",
    "InsiderBuyingAllocationState",
    "InsiderBuyingPreregistrationError",
    "InsiderBuyingResearchGate",
    "InsiderBuyingSlotDisposition",
    "LoadedSecBulkSnapshot",
    "LoadedSecBulkParsedSnapshot",
    "LoadedSecEdgarAcceptanceSnapshot",
    "PARSED_SNAPSHOT_CONTRACT_VERSION",
    "ParsedFiling",
    "ParsedSecBulkAccession",
    "ParsedSecBulkRow",
    "ParsedSecBulkTableIdentity",
    "ParsedTransaction",
    "PublicAvailability",
    "ProfileBoundForm4AmendmentEvidence",
    "ReconciledForm4Amendments",
    "ReportingOwner",
    "REQUIRED_SEC_TABLES",
    "SecBulkMember",
    "SecBulkParsedSnapshotError",
    "SecBulkParsedSnapshotIdentity",
    "SecBulkSnapshotError",
    "SecBulkSnapshotIdentity",
    "SecBulkSource",
    "SecTsvSchemaProfile",
    "SecTsvSchemaVariant",
    "SEC_TSV_PARSER_VERSION",
    "SEC_EDGAR_METADATA_PARSER_VERSION",
    "SecEdgarAcceptanceSnapshotError",
    "SecEdgarAcceptanceSnapshotIdentity",
    "SecEdgarAcceptancePeriodIdentity",
    "SecEdgarAcceptancePeriodInput",
    "SecEdgarAvailabilityRecord",
    "SecEdgarAvailabilityRule",
    "SecEdgarAvailabilityTier",
    "SecEdgarMetadataSchemaProfile",
    "SecEdgarMetadataSource",
    "SecEdgarMetadataSourceIdentity",
    "SecForm4XmlSource",
    "SecForm4XmlSourceIdentity",
    "SecForm4AmendmentEvidenceProfile",
    "SuppliedForm4AmendmentLinkEvidence",
    "TransactionDiagnostic",
    "build_filing_corpus",
    "build_form4_observed_identity_inventory",
    "build_form4_pit_security_mapping",
    "build_form4_provisional_disposition_report",
    "build_form4_provisional_lot_diagnostics",
    "build_form4_sec_entity_grouping",
    "assemble_sec_form4_multi_period_evidence",
    "build_sec_bulk_parsed_snapshot",
    "build_sec_edgar_acceptance_snapshot",
    "inspect_sec_bulk_archive",
    "load_sec_bulk_snapshot",
    "load_sec_bulk_parsed_snapshot",
    "load_sec_edgar_acceptance_snapshot",
    "load_form4_provisional_disposition_snapshot",
    "parse_form4_xml",
    "reconcile_sec_form4_amendments",
    "write_sec_bulk_snapshot",
    "write_form4_provisional_disposition_snapshot",
    "FORM4_STOCK_SIGNAL_DECIMAL_PRECISION",
    "FORM4_STOCK_SIGNAL_DECIMAL_ROUNDING",
    "FORM4_STOCK_SIGNAL_DOLLAR_BREADTH_FORMULA",
    "FORM4_STOCK_SIGNAL_EVENT_SCORE_FORMULA",
    "FORM4_STOCK_SIGNAL_FORMULA_DIAGNOSTICS_VERSION",
    "FORM4_STOCK_SIGNAL_FRESHNESS_EVALUATION",
    "FORM4_STOCK_SIGNAL_FRESHNESS_FORMULA",
    "FORM4_STOCK_SIGNAL_HALF_LIFE_TRADING_DAYS",
    "FORM4_STOCK_SIGNAL_LOOKBACK_TRADING_DAYS",
    "FORM4_STOCK_SIGNAL_MINIMUM_PURCHASE_VALUE_USD",
    "FORM4_STOCK_SIGNAL_NUMERIC_POLICY_HASH",
    "FORM4_STOCK_SIGNAL_RAW_SCORE_FORMULA",
    "FORM4_STOCK_SIGNAL_SIZE_FORMULA",
    "MAX_FORM4_STOCK_SIGNAL_AGE_TRADING_DAYS",
    "MAX_FORM4_STOCK_SIGNAL_EVENTS",
    "MAX_FORM4_STOCK_SIGNAL_PROJECTION_DEPTH",
    "MAX_FORM4_STOCK_SIGNAL_PROJECTION_NODES",
    "MAX_FORM4_STOCK_SIGNAL_ROLES_PER_EVENT",
    "MAX_FORM4_STOCK_SIGNAL_TEXT_CHARACTERS",
    "Form4StockSignalBreadthDiagnostics",
    "Form4StockSignalEventContribution",
    "Form4StockSignalFixtureEvent",
    "Form4StockSignalFormulaDiagnostics",
    "Form4StockSignalFormulaDiagnosticsError",
    "Form4StockSignalFormulaIdentity",
    "build_form4_stock_signal_fixture_event",
    "build_form4_stock_signal_formula_diagnostics",
]
