"""Offline, non-executing contracts for the Insider Buying research lane.

This package deliberately has no network collection, outcome, portfolio,
broker, or scheduler surface. It contains immutable in-memory Form 4
structure, a fixture parser, and a caller-supplied SEC quarterly ZIP integrity
boundary plus explicit-profile, offline parsed, EDGAR acceptance-evidence, and
observation-only Form 4/A chronology and multi-period supplied-link-evidence
boundaries, plus an evidence-bound provisional disposition/quarantine report
and its immutable, upstream-rebuilt snapshot boundary.  The package also
exposes the zero-authority IB-1I four-family research gate without allocating
a confirmatory cell or permanent look.
"""

from research.insider_buying.contracts import (
    CANONICAL_SPEC,
    ClassificationOutcome,
    FilingCorpus,
    FilingEnvelope,
    ParsedFiling,
    ParsedTransaction,
    PublicAvailability,
    ReportingOwner,
    TransactionDiagnostic,
    build_filing_corpus,
)
from research.insider_buying.form4_xml import Form4ParseError, parse_form4_xml
from research.insider_buying.form4_amendment_reconciliation import (
    FORM4_AMENDMENT_RECONCILIATION_VERSION,
    Form4AmendmentLineage,
    Form4AmendmentReconciliationError,
    Form4AmendmentReconciliationIdentity,
    Form4ObservedState,
    Form4VersionDisposition,
    Form4VersionInterval,
    ReconciledForm4Amendments,
    SecForm4XmlSource,
    SecForm4XmlSourceIdentity,
    reconcile_sec_form4_amendments,
)
from research.insider_buying.form4_multi_period_amendment_evidence import (
    FORM4_MULTI_PERIOD_EVIDENCE_VERSION,
    Form4MultiPeriodEvidenceError,
    Form4MultiPeriodEvidenceIdentity,
    ProfileBoundForm4AmendmentEvidence,
    SecEdgarAcceptancePeriodIdentity,
    SecEdgarAcceptancePeriodInput,
    SecForm4AmendmentEvidenceProfile,
    SuppliedForm4AmendmentLinkEvidence,
    assemble_sec_form4_multi_period_evidence,
)
from research.insider_buying.form4_provisional_disposition_report import (
    FORM4_PROVISIONAL_DISPOSITION_REPORT_VERSION,
    Form4ProvisionalDisposition,
    Form4ProvisionalDispositionReport,
    Form4ProvisionalDispositionReportError,
    Form4ProvisionalDispositionReportIdentity,
    Form4ProvisionalDispositionRow,
    build_form4_provisional_disposition_report,
)
from research.insider_buying.form4_provisional_disposition_snapshot import (
    FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_KIND,
    FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_VERSION,
    Form4ProvisionalDispositionSnapshotError,
    load_form4_provisional_disposition_snapshot,
    write_form4_provisional_disposition_snapshot,
)
from research.insider_buying.sec_bulk_snapshot import (
    ALLOWED_SEC_TABLES,
    LoadedSecBulkSnapshot,
    SecBulkMember,
    SecBulkSnapshotError,
    SecBulkSnapshotIdentity,
    SecBulkSource,
    REQUIRED_SEC_TABLES,
    inspect_sec_bulk_archive,
    load_sec_bulk_snapshot,
    write_sec_bulk_snapshot,
)
from research.insider_buying.sec_bulk_parsed_snapshot import (
    LoadedSecBulkParsedSnapshot,
    ParsedSecBulkAccession,
    ParsedSecBulkRow,
    ParsedSecBulkTableIdentity,
    PARSED_SNAPSHOT_CONTRACT_VERSION,
    SEC_TSV_PARSER_VERSION,
    SecBulkParsedSnapshotError,
    SecBulkParsedSnapshotIdentity,
    SecTsvSchemaProfile,
    SecTsvSchemaVariant,
    build_sec_bulk_parsed_snapshot,
    load_sec_bulk_parsed_snapshot,
)
from research.insider_buying.sec_edgar_acceptance_snapshot import (
    EDGAR_ACCEPTANCE_SNAPSHOT_CONTRACT_VERSION,
    EDGAR_ACCEPTANCE_SNAPSHOT_KIND,
    LoadedSecEdgarAcceptanceSnapshot,
    SEC_EDGAR_METADATA_PARSER_VERSION,
    SecEdgarAcceptanceSnapshotError,
    SecEdgarAcceptanceSnapshotIdentity,
    SecEdgarAvailabilityRecord,
    SecEdgarAvailabilityRule,
    SecEdgarAvailabilityTier,
    SecEdgarMetadataSchemaProfile,
    SecEdgarMetadataSource,
    SecEdgarMetadataSourceIdentity,
    build_sec_edgar_acceptance_snapshot,
    load_sec_edgar_acceptance_snapshot,
)
from research.insider_buying.preregistration import (
    FIXED_STRATEGY_LANE_IDS,
    INSIDER_BUYING_BLUEPRINT_SHA256,
    INSIDER_BUYING_RESEARCH_GATE,
    INSIDER_BUYING_RESEARCH_GATE_SHA256,
    INSIDER_BUYING_RESEARCH_GATE_VERSION,
    InsiderBuyingAllocationState,
    InsiderBuyingPreregistrationError,
    InsiderBuyingResearchGate,
    InsiderBuyingSlotDisposition,
)

__all__ = [
    "ALLOWED_SEC_TABLES",
    "CANONICAL_SPEC",
    "ClassificationOutcome",
    "EDGAR_ACCEPTANCE_SNAPSHOT_CONTRACT_VERSION",
    "EDGAR_ACCEPTANCE_SNAPSHOT_KIND",
    "FORM4_AMENDMENT_RECONCILIATION_VERSION",
    "FORM4_MULTI_PERIOD_EVIDENCE_VERSION",
    "FORM4_PROVISIONAL_DISPOSITION_REPORT_VERSION",
    "FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_KIND",
    "FORM4_PROVISIONAL_DISPOSITION_SNAPSHOT_VERSION",
    "FIXED_STRATEGY_LANE_IDS",
    "FilingCorpus",
    "FilingEnvelope",
    "Form4AmendmentLineage",
    "Form4AmendmentReconciliationError",
    "Form4AmendmentReconciliationIdentity",
    "Form4MultiPeriodEvidenceError",
    "Form4MultiPeriodEvidenceIdentity",
    "Form4ProvisionalDisposition",
    "Form4ProvisionalDispositionReport",
    "Form4ProvisionalDispositionReportError",
    "Form4ProvisionalDispositionReportIdentity",
    "Form4ProvisionalDispositionRow",
    "Form4ProvisionalDispositionSnapshotError",
    "Form4ObservedState",
    "Form4ParseError",
    "Form4VersionDisposition",
    "Form4VersionInterval",
    "INSIDER_BUYING_BLUEPRINT_SHA256",
    "INSIDER_BUYING_RESEARCH_GATE",
    "INSIDER_BUYING_RESEARCH_GATE_SHA256",
    "INSIDER_BUYING_RESEARCH_GATE_VERSION",
    "InsiderBuyingAllocationState",
    "InsiderBuyingPreregistrationError",
    "InsiderBuyingResearchGate",
    "InsiderBuyingSlotDisposition",
    "LoadedSecBulkSnapshot",
    "LoadedSecBulkParsedSnapshot",
    "LoadedSecEdgarAcceptanceSnapshot",
    "PARSED_SNAPSHOT_CONTRACT_VERSION",
    "ParsedFiling",
    "ParsedSecBulkAccession",
    "ParsedSecBulkRow",
    "ParsedSecBulkTableIdentity",
    "ParsedTransaction",
    "PublicAvailability",
    "ProfileBoundForm4AmendmentEvidence",
    "ReconciledForm4Amendments",
    "ReportingOwner",
    "REQUIRED_SEC_TABLES",
    "SecBulkMember",
    "SecBulkParsedSnapshotError",
    "SecBulkParsedSnapshotIdentity",
    "SecBulkSnapshotError",
    "SecBulkSnapshotIdentity",
    "SecBulkSource",
    "SecTsvSchemaProfile",
    "SecTsvSchemaVariant",
    "SEC_TSV_PARSER_VERSION",
    "SEC_EDGAR_METADATA_PARSER_VERSION",
    "SecEdgarAcceptanceSnapshotError",
    "SecEdgarAcceptanceSnapshotIdentity",
    "SecEdgarAcceptancePeriodIdentity",
    "SecEdgarAcceptancePeriodInput",
    "SecEdgarAvailabilityRecord",
    "SecEdgarAvailabilityRule",
    "SecEdgarAvailabilityTier",
    "SecEdgarMetadataSchemaProfile",
    "SecEdgarMetadataSource",
    "SecEdgarMetadataSourceIdentity",
    "SecForm4XmlSource",
    "SecForm4XmlSourceIdentity",
    "SecForm4AmendmentEvidenceProfile",
    "SuppliedForm4AmendmentLinkEvidence",
    "TransactionDiagnostic",
    "build_filing_corpus",
    "build_form4_provisional_disposition_report",
    "assemble_sec_form4_multi_period_evidence",
    "build_sec_bulk_parsed_snapshot",
    "build_sec_edgar_acceptance_snapshot",
    "inspect_sec_bulk_archive",
    "load_sec_bulk_snapshot",
    "load_sec_bulk_parsed_snapshot",
    "load_sec_edgar_acceptance_snapshot",
    "load_form4_provisional_disposition_snapshot",
    "parse_form4_xml",
    "reconcile_sec_form4_amendments",
    "write_sec_bulk_snapshot",
    "write_form4_provisional_disposition_snapshot",
]
